[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
  conditions = {Cookie = ["sb-*"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
